zigpy/zigpy-xbee

tests/test_api.py, tests/test_application.py, tests/test_uart.py, zigpy_xbee/api.py, zigpy_xbee/uart.py, zigpy_xbee/zigbee/application.py
This PR allows zigpy-xbee to configure a XBee device which was reset to default settings, regardless of configured baudrate. 
If there's no reply to the very 1st AT command API frame, then it would try to escape into "AT Command mode" by sending +++ and configuring API mode via AT commands. If there's no response to "escape sequence", then it would probe different baudrates until it gets a response or fails.
This PR works best with https://github.com/Adminiuga/zigpy-xbee/tree/fix-xbee-resets
=> automatic API mode configuration of XBee device

tests/test_api.py, tests/test_application.py, tests/test_types.py, zigpy_xbee/api.py, zigpy_xbee/types.py, zigpy_xbee/zigbee/application.py
Fixes #23 and https://github.com/zigpy/zigpy-xbee/issues/22#issuecomment-453878521
S2B and older modules do not support `ATCE1` command. If device replies with `ERROR` to ATCE1 command, make it a soft failure.
=> Handle initialization of the legacy S2 module

zigpy_xbee/zigbee/application.py
Set indirect transmission timeout to 7.68s
Set end device poll timeout to 256 minutes per Zigbee R21 spec.
=> Set poll timeout for end devices.

tests/test_api.py, tests/test_application.py, tests/test_types.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
Eliminate `zigpy_xbee.api._seq_command()` method.
Split COMMANDS into COMMAND_REQUESTS and COMMAND_RESPONSES.
=> Refactor api commands.

zigpy_xbee/api.py
Transmission Status of `TXStatus.SELF_ADDRESSED` is a successful transmission so treat it as such.
=> treat TXStatus.SELF_ADDRESSED as a successful tramsmission.

setup.py, tests/test_application.py, zigpy_xbee/zigbee/application.py
Tell Zigbee stack to use Extended Timeout between retries when communicating with an End Device.
Use longer reply timeout if far end is an End Device.
=> Dynamic reply timeout.

setup.py, tests/test_const.py, zigpy_xbee/__init__.py, zigpy_xbee/const.py
=> Version bump 0.2.1

setup.py, tests/test_application.py, tests/test_const.py, zigpy_xbee/__init__.py, zigpy_xbee/const.py, zigpy_xbee/zigbee/application.py
=> 0.2.1 Release

tests/test_application.py, zigpy_xbee/zigbee/application.py
Fixes `Failed to parse message, data is too short` when a device joins/rejoins network.
```
2019-06-30 18:45:27 DEBUG (MainThread) [zigpy_xbee.uart] Frame received: b'\x91\x00\x0bW\xff\xfeKK@\xa0!\x00\x00\x00\x13\x00\x00\x02\x81!\xa0@KK\xfe\xffW\x0b\x00\x80'
2019-06-30 18:45:27 DEBUG (MainThread) [zigpy_xbee.api] Frame received: explicit_rx_indicator
2019-06-30 18:45:27 DEBUG (MainThread) [zigpy_xbee.api] _handle_explicit_rx: (00:0b:57:ff:fe:4b:4b:40, 0xa021, 0, 19, 2, b'8121a0404b4bfeff570b0080')
2019-06-30 18:45:27 INFO (MainThread) [zigpy_xbee.zigbee.application] New device joined: NWK 0xa021, IEEE 00:0b:57:ff:fe:4b:4b:40
2019-06-30 18:45:27 INFO (MainThread) [zigpy.application] Device 0xa021 (00:0b:57:ff:fe:4b:4b:40) joined the network
2019-06-30 18:45:27 ERROR (MainThread) …
```
=> Don't consume data when processing ZDO device_annce message.

setup.py, tests/test_application.py, tests/test_types.py, zigpy_xbee/__init__.py, zigpy_xbee/types.py, zigpy_xbee/zigbee/application.py
=> 0.6.0 Release.

zigpy_xbee/zigbee/application.py
Disable APS encryption, as some devices do not support it and ATM `bellows` doesn't do APS encryption by default.
Fixes #30
=> Disable APS encryption.

Contributors.md, README.md, zigpy_xbee/__init__.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
=> 0.8.0 Release

README.md, setup.py
Revert package name back to `zigpy-xbee`.
=> Revert package name back to zigpy-xbee

LICENSE, README.md, setup.py, tests/test_api.py, tests/test_application.py, tests/test_uart.py, zigpy_xbee/__init__.py, zigpy_xbee/api.py, zigpy_xbee/config.py, zigpy_xbee/uart.py, zigpy_xbee/zigbee/application.py
=> 0.12.0 Release

README.md, zigpy_xbee/__init__.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
=> 0.12.1 Release

tests/test_application.py, zigpy_xbee/zigbee/application.py
May be I am missing something, but the specs says that "Send the remote command securely" is Bit 4 [0x10].
=> Fix Remote AT command options

README.md
Update list of compatible hardware to zigpy-xbee README.md as the plan is to remove such a list from zigpy in https://github.com/zigpy/zigpy/pull/705
Downstream project(s) also want such information to be provided by upstream as per https://github.com/home-assistant/home-assistant.io/pull/17089
=> Update compatible hardware in zigpy-xbee

zigpy_xbee/zigbee/application.py
- NodeDescriptor is set to "Router" but it should reflect the requirement "Zigbee Coordinator API firmware".
- Issue raw_device_initialized after xbee_dev is available; otherwise https://github.com/zigpy/zigpy/blob/dev/zigpy/appdb.py#L385 is not satisfied leaving an uncommited INSERT hanging around which leads to blocking ZHA & malfunction after restart (missing device) in SQLite
=> Adjust NodeDescriptor & fix hanging ZHA

zigpy_xbee/__init__.py, zigpy_xbee/zigbee/application.py
=> 0.16.1 Release

.pre-commit-config.yaml, zigpy_xbee/__init__.py, zigpy_xbee/zigbee/application.py
=> 0.17.0 Release

tests/test_application.py, zigpy_xbee/zigbee/application.py
Load network info on startup if it isn't already loaded, to validate the coordinator NWK address.
=> Ensure network startup is consistent

setup.py, zigpy_xbee/zigbee/application.py
There was a syntax change with the `retryable_request` decorator in zigpy 0.56.0
=> Bump minimum zigpy version to 0.56.0

zigpy_xbee/zigbee/application.py
This PR fixes error on startup about endpoint 1 not being found. The error started to appear after https://github.com/zigpy/zigpy/pull/1238
The PR registers zigpy endpoints on network start.
=> register zigpy endpoints at startup

zigpy_xbee/__init__.py, zigpy_xbee/zigbee/application.py
=> 0.18.2 Release

zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
Reconnect tasks should be cancelled when the application disconnects.
=> Cleanup tasks on disconnect

zigpy_xbee/__init__.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
=> 0.18.3 Release

tests/test_application.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
Add support for per-channel energy detect for XBee coordinators.
Logs:
```
2023-09-26 09:05:26.779 DEBUG (MainThread) [zigpy_xbee.api] at command: ED (4,)
2023-09-26 09:05:26.779 DEBUG (MainThread) [zigpy_xbee.api] Command at (b'ED', b'\x00\x00\x00\x00')
2023-09-26 09:05:26.779 DEBUG (MainThread) [zigpy_xbee.uart] Sending: b'\x08\x14ED\x00\x00\x00\x00'
2023-09-26 09:05:27.153 DEBUG (MainThread) [homeassistant.bootstrap] Running timeout Zones: {'xbee_humidifier': <xbee_humidifier: 0 / 1>}
2023-09-26 09:05:27.154 DEBUG (MainThread) [homeassistant.bootstrap] Integration remaining: {'zha': 14.551212}
2023-09-26 09:05:27.467 DEBUG (MainThread) [zigpy_xbee.uart] Frame received: b'\x88\x14ED\x00/D1>\x06"\x16.*90IEKK7'
2023-09-26 09:05:27.467 DEBUG (MainThread) [zigpy_xbee.api] Frame received: …
```
=> Channel energy scan

tests/test_api.py, tests/test_application.py, zigpy_xbee/api.py, zigpy_xbee/zigbee/application.py
Add support for device joining via install codes.
Successful logs:
```
INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=zha, service=permit, service_data=duration=60, install_code=C9A7D2441A711695CD62170D3328EA2B423D, source_ieee=0013A200419823F9>
INFO (MainThread) [homeassistant.components.zha.websocket_api] Allowing join for 00:13:a2:00:41:98:23:f9 device with install code
DEBUG (MainThread) [zigpy_xbee.api] at command: KT (60,)
DEBUG (MainThread) [zigpy_xbee.api] Command at (b'KT', b'\x00<')
DEBUG (MainThread) …
```
=> Joining with link key
