zigpy/zigpy-xbee

- README.md
Updated README.md with a couple of more links for reference
> Updated README.md with a couple of more links for reference

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
Rename permit() method.
This is an accompanying PR for https://github.com/zigpy/zigpy/pull/91
> Implement ControllerApplication.broadcast() method.

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
Use ZDO device_annce message to trigger new device join.
> Refactor device join.

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
goes along with https://github.com/zigpy/zigpy/pull/133
> Add ControllerApplication.shutdown() method.

- tests/test_application.py
- zigpy_xbee/types.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
Lookup devices by NWK, fallback to IEEE if it's known.
> Refactor device lookup.

- tests/test_api.py
- tests/test_application.py
- zigpy_xbee/api.py
- zigpy_xbee/types.py
- zigpy_xbee/zigbee/application.py
Handle tx_status frames. Not waiting for a reply any longer, if we know that out transmission has failed.
> Handle tx_status notification frames. 

- zigpy_xbee/zigbee/application.py
Subscribe/Unsubscribe XBee coordinator to Groups via [XBee Group API](https://www.digi.com/resources/documentation/Digidocs/90002002/Content/Concepts/c_zb_group_table_api.htm)
Works for XBee S2C and later. Max 12 groups are supported.
> XBee Group subscription.

- zigpy_xbee/zigbee/application.py
Update XBee coordinator quirks signature.
> Update XBee coordinator quirks signature.

- setup.py
- tests/test_application.py
- zigpy_xbee/__init__.py
- zigpy_xbee/zigbee/application.py
> 0.4.0 Release.

- .pre-commit-config.yaml
- setup.cfg
- tests/test_api.py
- tests/test_application.py
- tests/test_types.py
- tests/test_uart.py
- tox.ini
- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
- zigpy_xbee/types.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
Install pre-commit and black format code.
> .pre-commit hook

- setup.py
- tests/test_application.py
- zigpy_xbee/__init__.py
- zigpy_xbee/zigbee/application.py
Sync up with changes in zigpy.
> Sync up with zigpy refactoring.

- .pre-commit-config.yaml
- setup.cfg
- setup.py
- tests/test_api.py
- tests/test_application.py
- tests/test_types.py
- tests/test_uart.py
- tox.ini
- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
- zigpy_xbee/types.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
> 0.5.0 Release.

- setup.py
- tests/test_application.py
- tests/test_types.py
- zigpy_xbee/types.py
- zigpy_xbee/zigbee/application.py
Syncup to `zigpy-homeassistant==0.10.0`.
> Refactor EUI64 class.

- README.md
Update README.md to flesh it out with more information and links.
Hoping this could possible attract both more developers and users.
> Update README.md to flesh it out with more information and links

- .github/release-drafter.yml
- .github/workflows/release-management.yml
- setup.cfg
- zigpy_xbee/api.py
Use https://github.com/apps/release-drafter for release drafter.
> Add release drafter.

- tox.ini
> Add black check to tox.

- tox.ini
> Drop Python 3.5 support.

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
Allow sending multicast addressed transmissions.
> Send multicast support.

- .travis.yml
> Update travis configuration.

- tests/test_uart.py
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
Don't try to interpret incoming data as AT command mode response unless specifically enter into AT command mode.
Fixes #59
Fixes #48
> Don't try to interpret incoming data as AT command mode response.

- .github/release-drafter.yml
- .github/workflows/release-management.yml
- .travis.yml
- README.md
- setup.cfg
- tests/test_application.py
- tests/test_uart.py
- tox.ini
- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
> 0.7.0 Release.

- zigpy_xbee/api.py
Enable M0 and M1 remote AT commands
> PWM duty cycle AT commands

- zigpy_xbee/zigbee/application.py
> Timeout if we never get association state.

- zigpy_xbee/api.py
Add missing GPIO pins.
Fixes #78
> Add missing GPIO pins

- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
> 0.9.0 Release.

- zigpy_xbee/zigbee/application.py
Update last_seen for coordinator when we receive any incoming message.
> Add coordinator device with correct status

- zigpy_xbee/__init__.py
- zigpy_xbee/zigbee/application.py
> 0.10.0 Release

- .pre-commit-config.yaml
- .travis.yml
- tests/test_application.py
- tests/test_types.py
- tox.ini
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
Add isort checks to pre-commit, tox and travis.
> Add isort checks.

- setup.py
- tests/test_api.py
- tests/test_uart.py
- tox.ini
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
Handle port disconnects and try reconnect the port on disconnects.
> Handle port disconnects

- tests/test_api.py
- tests/test_uart.py
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
Implement a method allowing upper layer applications to detect whether a correct radio module is present on a given serial port .
Implements zigpy_xbee.api.XBee.probe(port, baudrate) -> bool async class method, which return `True` if radio was detected on port path or `False` otherwise. All exceptions are consumed by the method.
> Implement radio probe

- .github/workflows/publish-to-pypi.yml
- .pre-commit-config.yaml
- .travis.yml
- setup.py
- tests/test_api.py
- tests/test_application.py
- tests/test_types.py
- tests/test_uart.py
- tox.ini
- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
- zigpy_xbee/uart.py
> 0.11.0 Release

- setup.py
> Add PyPi long description

- setup.py
- tests/test_api.py
- tests/test_application.py
- tests/test_uart.py
- zigpy_xbee/api.py
- zigpy_xbee/config.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
Sync up to `zigpy==0.20.0` changes. 
Use new zigpy initialization method.
> Use new zigpy initialization.

- setup.py
- tests/test_api.py
- tests/test_application.py
- tests/test_uart.py
- zigpy_xbee/__init__.py
- zigpy_xbee/api.py
- zigpy_xbee/config.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
Sync with `zigpy==0.20.0` changes
> Syncup with zigpy==0.20.0

- zigpy_xbee/api.py
- zigpy_xbee/zigbee/application.py
Add probe and device schema to App Controller.
> Add probe and device schema to App Controller

- README.md
Update README.md with new (old) link to PyPI project for zigpy-xbee
> Update README.md with new (old) link to PyPI project for zigpy-xbee

- README.md
Updated README.md with info on how-to test new releases.
Copied this text from zigpy-cc so credits go to @sanyatuning
> Updated README.md with info on how-to test new releases.

- .travis.yml
- setup.py
- tox.ini
- zigpy_xbee/api.py
- zigpy_xbee/types.py
Make zigpy-xbee compatible with zigpy==0.23.0
> Make zigpy-xbee compatible with zigpy==0.23.0

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
Same fix as https://github.com/zigpy/bellows/pull/421
> Handle `None` node descriptor

- setup.py
otherwise it still tries to install the 'tests' package at top level...
> Update setup.py, make the exclude for 'tests' work

- .github/workflows/publish-to-pypi.yml
- setup.py
- tests/test_application.py
- zigpy_xbee/types.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
Implements https://github.com/zigpy/zigpy/pull/1043
> Implement zigpy packet api

- .github/workflows/publish-to-pypi.yml
- setup.py
- tests/test_application.py
- zigpy_xbee/__init__.py
- zigpy_xbee/types.py
- zigpy_xbee/uart.py
- zigpy_xbee/zigbee/application.py
> 0.16.0 Release

- zigpy_xbee/zigbee/application.py
https://github.com/home-assistant/core/issues/79885
It appears that the XBee always requires the device IEEE address to be passed, even when sending a request with NWK addressing.
---
@michelwilson can you try this change out?
```bash
pip install --force-reinstall git+https://github.com/puddly/zigpy-xbee.git@puddly/fix-unicast-without-ieee
```
> XBee cannot send packets without an IEEE address

- zigpy_xbee/zigbee/application.py
https://github.com/home-assistant/core/issues/80023
> Ensure numeric values are passed for possibly `None` attributes

- zigpy_xbee/__init__.py
- zigpy_xbee/zigbee/application.py
> 0.16.2 Release

- .pre-commit-config.yaml
- zigpy_xbee/zigbee/application.py
`is_reply` is going to be removed soon so this should be fixed.
> Replace deprecated `is_reply` attribute

- tests/test_application.py
- zigpy_xbee/zigbee/application.py
https://github.com/zigpy/zigpy/pull/1190
> Implement channel migration

- zigpy_xbee/zigbee/application.py
Probably fixes https://github.com/home-assistant/core/issues/92375.
> Disable energy scanning

- setup.py
- zigpy_xbee/__init__.py
- zigpy_xbee/zigbee/application.py
> 0.18.1 Release

- zigpy_xbee/api.py
Increase timeout for waiting AT command responses from the device.
https://github.com/home-assistant/core/issues/100348
> Increase AT timeout
